version: '3.8'

services:
  evolution-go-teste:
    image: ghcr.io/admintnl/evolution-go:latest
    restart: unless-stopped
    ports:
      - "4001:4000"
    environment:
      SERVER_PORT: 4000
      CLIENT_NAME: "evolution"
      GLOBAL_API_KEY: "teste-patch-9x7k4"
      POSTGRES_AUTH_DB: "postgresql://postgres:postgres@postgres-teste:5432/evogo_auth?sslmode=disable"
      POSTGRES_USERS_DB: "postgresql://postgres:postgres@postgres-teste:5432/evogo_users?sslmode=disable"
      DATABASE_SAVE_MESSAGES: "false"
      WADEBUG: "INFO"
      LOGTYPE: "console"
      LOG_DIRECTORY: "/app/logs"
      LOG_MAX_SIZE: "100"
      LOG_MAX_BACKUPS: "5"
      LOG_MAX_AGE: "30"
      LOG_COMPRESS: "true"
      CONNECT_ON_STARTUP: "false"
      WEBHOOK_FILES: "true"
      OS_NAME: "Linux"
      WEBHOOK_URL: ""
      AMQP_URL: ""
      AMQP_GLOBAL_ENABLED: "false"
      NATS_URL: ""
      NATS_GLOBAL_ENABLED: "false"
      MINIO_ENABLED: "false"
      PROXY_HOST: ""
      PROXY_PORT: ""
      PROXY_USERNAME: ""
      PROXY_PASSWORD: ""
      EVENT_IGNORE_GROUP: "false"
      EVENT_IGNORE_STATUS: "true"
      QRCODE_MAX_COUNT: "5"
    volumes:
      - evolution_data:/app/dbdata
      - evolution_logs:/app/logs
    networks:
      - evolution_network
      - adminNet
    depends_on:
      - postgres-teste

  postgres-teste:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - evolution_network

volumes:
  evolution_data:
    driver: local
  evolution_logs:
    driver: local
  postgres_data:
    driver: local

networks:
  evolution_network:
    driver: overlay
  adminNet:
    external: true
